# Build settings
# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /blog/:title:output_ext

title: Credit Risk Analytics & Real-Time Scoring
description: A machine learning project on credit risk modelling and real-time applicant scoring. Follow for updates and insights!
